export const VERSION='analytics-1.0';
export const targets={last2:{name:'เลขท้าย 2 ตัว',digits:2},top2:{name:'2 ตัวบน · อนุพันธ์รางวัลที่ 1',digits:2},top3:{name:'3 ตัวบน · อนุพันธ์รางวัลที่ 1',digits:3},first3OfFirst:{name:'3 หลักแรกของรางวัลที่ 1',digits:3},front3:{name:'เลขหน้า 3 ตัว · หลายรางวัล',digits:3,multi:true},last3:{name:'เลขท้าย 3 ตัว · หลายรางวัล',digits:3,multi:true}};
export function values(d,target){if(target==='top2')return d.firstPrize?[d.firstPrize.slice(-2)]:[];if(target==='top3')return d.firstPrize?[d.firstPrize.slice(-3)]:[];if(target==='first3OfFirst')return d.firstPrize?[d.firstPrize.slice(0,3)]:[];return d[target]==null?[]:Array.isArray(d[target])?d[target]:[d[target]];}
export function history(draws,target,cutoff='9999-12-31'){return draws.filter(d=>d.drawDate<cutoff&&d.verification!=='conflict'&&d.verification!=='demo').sort((a,b)=>a.drawDate.localeCompare(b.drawDate)).map(d=>({...d,values:values(d,target)})).filter(d=>d.values.length);}
export function rng(seed=42){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
export const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:null;
export function wilson(h,n){if(!n)return null;const z=1.96,p=h/n,d=1+z*z/n,c=(p+z*z/(2*n))/d,w=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/d;return [Math.max(0,c-w),Math.min(1,c+w)];}
export function baseline(k,u,m=1,replacement=true){if(k<0||k>u||m<1)throw Error('Invalid baseline');if(replacement)return 1-(1-k/u)**m;let miss=1;for(let i=0;i<m;i++)miss*=Math.max(0,u-k-i)/(u-i);return 1-miss;}
export function holm(ps){const out=Array(ps.length);let prev=0;ps.map((p,i)=>({p,i})).sort((a,b)=>a.p-b.p).forEach(({p,i},j)=>{prev=Math.max(prev,Math.min(1,p*(ps.length-j)));out[i]=prev;});return out;}
export function binomialUpper(h,n,p){if(h===0)return 1;let log=0,sum=0;for(let k=0;k<=n;k++){if(k>0)log+=Math.log(n-k+1)-Math.log(k);if(k>=h)sum+=Math.exp(log+k*Math.log(p)+(n-k)*Math.log1p(-p));}return Math.min(1,sum);}
export function features(x){const d=[...x].map(Number),sum=d.reduce((a,b)=>a+b,0),distinct=new Set(d).size;return{sum,root:sum===0?0:1+(sum-1)%9,difference:Math.abs(d[0]-d.at(-1)),range:Math.max(...d)-Math.min(...d),product:d.reduce((a,b)=>a*b,1),mod3:sum%3,mod9:sum%9,parity:d.map(n=>n%2?'คี่':'คู่').join('–'),highlow:d.map(n=>n<5?'ต่ำ':'สูง').join('–'),even:d.filter(n=>n%2===0).length,high:d.filter(n=>n>=5).length,zero:d.includes(0),permutation:[...x].sort().join(''),distinct,double:d.length===2&&distinct===1,triple:d.length===3&&distinct===1,sandwich:d.length===3&&d[0]===d[2]&&d[0]!==d[1],twoSame:d.length===3&&distinct===2,allDifferent:distinct===d.length,ascending:d.length===3&&d[1]===d[0]+1&&d[2]===d[1]+1,descending:d.length===3&&d[1]===d[0]-1&&d[2]===d[1]-1,adjacent:d.some((a,i)=>d.some((b,j)=>i<j&&Math.abs(a-b)===1))};}
export function statistics(draws,target,cutoff){const h=history(draws,target,cutoff),digits=targets[target].digits,u=10**digits,all=h.flatMap(d=>d.values),counts=Array(u).fill(0),positions=Array.from({length:digits},()=>Array(10).fill(0)),patterns={};all.forEach(x=>{counts[Number(x)]++;[...x].forEach((d,i)=>positions[i][+d]++);Object.entries(features(x)).forEach(([k,v])=>{patterns[k]??={};patterns[k][v]=(patterns[k][v]??0)+1;});});const gaps=counts.map((count,i)=>{const x=String(i).padStart(digits,'0'),indices=h.flatMap((d,j)=>d.values.includes(x)?[j]:[]),intervals=indices.slice(1).map((v,j)=>v-indices[j]),sorted=[...intervals].sort((a,b)=>a-b),avg=mean(intervals),gap=indices.length?h.length-1-indices.at(-1):h.length;return{number:x,count,current:gap,censored:!indices.length,completed:intervals.length,mean:avg,median:sorted.length?(sorted[Math.floor((sorted.length-1)/2)]+sorted[Math.ceil((sorted.length-1)/2)])/2:null,sd:intervals.length>1?Math.sqrt(intervals.reduce((s,g)=>s+(g-avg)**2,0)/(intervals.length-1)):null,max:intervals.length?Math.max(...intervals):null,overdue:avg?gap/avg:null,percentile:intervals.length?intervals.filter(g=>g<=gap).length/intervals.length:null};});const entropy=all.length?-counts.reduce((s,c)=>c?s+c/all.length*Math.log(c/all.length):s,0):null;return{draws:h.length,observations:all.length,counts,positions,patterns,gaps,expected:all.length/u,entropy,normalizedEntropy:entropy===null?null:entropy/Math.log(u),chiSquare:all.length?counts.reduce((s,c)=>s+(c-all.length/u)**2/(all.length/u),0):null,chiSquareEligible:all.length/u>=5,cutoff:h.at(-1)?.drawDate??null};}
export const models=[['uniform','สุ่มสม่ำเสมอ'],['frequency','ความถี่ปรับเรียบ'],['recent','ความถี่ 20 งวด'],['decay','ถ่วงเวลาครึ่งชีวิต 20 งวด'],['position','อิสระรายหลัก'],['markov','Markov รายหลัก'],['sum','หมวดผลรวมปรับขนาด'],['ensemble','เฉลี่ย 3 แบบจำลอง'],['fixed','ชุดคงที่ประกาศล่วงหน้า'],['random1','สุ่ม seed 11'],['random2','สุ่ม seed 29'],['random3','สุ่ม seed 71']];
export function predict(draws,target,{cutoff='9999-12-31',model='frequency',alpha=1,window=20,seed=42}={}){if(!targets[target]||targets[target].multi)throw Error('Ranking supports single-result targets only');if(!(alpha>0)||!Number.isInteger(window)||window<1)throw Error('Invalid parameters');const h=history(draws,target,cutoff),digits=targets[target].digits,u=10**digits;let p=Array(u).fill(1/u);const counts=Array(u).fill(alpha);const used=model==='recent'?h.slice(-window):h;const xs=used.map(d=>d.values[0]);
 if(['frequency','recent','decay'].includes(model)){xs.forEach((x,i)=>counts[+x]+=model==='decay'?2**(-(xs.length-1-i)/20):1);const total=counts.reduce((a,b)=>a+b,0);p=counts.map(c=>c/total);}
 if(['position','markov'].includes(model)){const rows=Array.from({length:digits},()=>Array(10).fill(alpha));if(model==='position')xs.forEach(x=>[...x].forEach((v,j)=>rows[j][+v]++));else if(xs.length)for(let t=1;t<xs.length;t++)for(let j=0;j<digits;j++)if(xs[t-1][j]===xs.at(-1)[j])rows[j][+xs[t][j]]++;const probs=rows.map(row=>row.map(c=>c/row.reduce((a,b)=>a+b,0)));p=p.map((_,i)=>[...String(i).padStart(digits,'0')].reduce((a,d,j)=>a*probs[j][+d],1));}
 if(model==='sum'){const sizes=Array(9*digits+1).fill(0),cs=Array(9*digits+1).fill(0);p.forEach((_,i)=>sizes[features(String(i).padStart(digits,'0')).sum]++);xs.forEach(x=>cs[features(x).sum]++);p=p.map((_,i)=>{const s=features(String(i).padStart(digits,'0')).sum;return(cs[s]+alpha*sizes[s])/(xs.length+alpha*u)/sizes[s];});}
 if(model==='ensemble'){const members=['frequency','position','sum'].map(m=>predict(draws,target,{cutoff,model:m,alpha,window,seed}).probabilities);p=p.map((_,i)=>mean(members.map(a=>a[i])));}
 const rand=rng(seed),ties=Array.from({length:u},()=>rand());if(model.startsWith('random')){const r=rng(({random1:11,random2:29,random3:71}[model])+h.length);for(let i=0;i<u;i++)ties[i]=r();}if(model==='fixed')for(let i=0;i<u;i++)ties[i]=-i;
 const order=Array.from({length:u},(_,i)=>i).sort((a,b)=>p[b]-p[a]||ties[b]-ties[a]);return{model,version:VERSION,probabilities:p,ranking:order.map(i=>({number:String(i).padStart(digits,'0'),probability:p[i],count:xs.filter(x=>+x===i).length})),samples:h.length,cutoff:h.at(-1)?.drawDate??null,seed,alpha,window,status:'experimental'};}
export function backtest(draws,target,{minTrain=30,seed=42,modelIds=models.map(m=>m[0])}={}){if(targets[target].multi)throw Error('Multi-prize backtest disabled pending draw-cluster analysis');const h=history(draws,target),u=10**targets[target].digits,start=Math.max(minTrain,Math.floor(h.length*.6)),holdout=Math.max(start,Math.floor(h.length*.8));const rows=[];for(let t=start;t<h.length;t++){for(const model of modelIds){const pred=predict(h.slice(0,t),target,{cutoff:h[t].drawDate,model,seed}),actual=h[t].values[0],p=pred.probabilities;rows.push({date:h[t].drawDate,trainEnd:h[t-1].drawDate,model,phase:t>=holdout?'holdout':'validation',actual,top20:pred.ranking.slice(0,20).map(x=>x.number),hits:Object.fromEntries([1,5,10,20].map(k=>[k,pred.ranking.slice(0,k).some(x=>x.number===actual)])),brier:p.reduce((s,v,i)=>s+(v-(i===+actual?1:0))**2,0),logLoss:-Math.log(p[+actual]),actualProbability:p[+actual]});}}
 const summaries=modelIds.map(model=>{const rs=rows.filter(r=>r.model===model&&r.phase==='holdout');return{model,n:rs.length,hits:Object.fromEntries([1,5,10,20].map(k=>{const hits=rs.filter(r=>r.hits[k]).length;return[k,{hits,rate:rs.length?hits/rs.length:null,ci:wilson(hits,rs.length),baseline:k/u,p:rs.length?binomialUpper(hits,rs.length,k/u):null}];})),brier:mean(rs.map(r=>r.brier)),logLoss:mean(rs.map(r=>r.logLoss))};});const ps=summaries.flatMap(s=>[1,5,10,20].map(k=>s.hits[k].p??1)),adj=holm(ps);summaries.forEach((s,i)=>[1,5,10,20].forEach((k,j)=>s.hits[k].adjustedP=adj[i*4+j]));return{manifest:{version:VERSION,target,seed,minTrain,parameters:{alpha:1,window:20},trainDates:[h[0]?.drawDate,h[start-1]?.drawDate],validationDates:[h[start]?.drawDate,h[holdout-1]?.drawDate],holdoutDates:[h[holdout]?.drawDate,h.at(-1)?.drawDate],cutoffPolicy:'strict drawDate < evaluation date',trialCount:modelIds.length,pFamily:`${modelIds.length} models × 4 K; Holm; one-sided binomial`,selection:'No tuning; fixed parameters; historical holdout is exploratory, not a frozen prospective test',event:'single result, exact match',status:'experimental'},summaries,rows};}
export function csv(rows){if(!rows.length)return '';const keys=Object.keys(rows[0]),cell=v=>'"'+String(v==null?'':typeof v==='object'?JSON.stringify(v):v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';return [keys.map(cell).join(','),...rows.map(r=>keys.map(k=>cell(r[k])).join(','))].join('\r\n');}
export function validateImport(rows){const accepted=[],quarantine=[],seen=new Set();for(const row of rows){const errors=[];if(!/^\d{4}-\d{2}-\d{2}$/.test(row.drawDate??'')||Number.isNaN(Date.parse(row.drawDate))||new Date(row.drawDate).toISOString().slice(0,10)!==row.drawDate)errors.push('วันที่ไม่ถูกต้อง');if(seen.has(row.drawDate))errors.push('วันที่ซ้ำ');seen.add(row.drawDate);for(const[k,len]of[['firstPrize',6],['last2',2]])if(row[k]!==null&&(typeof row[k]!=='string'||!new RegExp(`^\\d{${len}}$`).test(row[k])))errors.push(k+' ต้องเป็นข้อความความยาว '+len);for(const k of ['front3','last3'])if(row[k]!==null&&(!Array.isArray(row[k])||row[k].some(x=>typeof x!=='string'||!/^\d{3}$/.test(x))))errors.push(k+' ไม่ถูกต้อง');if(!row.sourceUrl||!row.rawHash)errors.push('ต้องมี sourceUrl และ rawHash');if(errors.length)quarantine.push({row,errors});else accepted.push({...row,verification:row.verification==='demo'?'demo':row.verification==='conflict'?'conflict':'single_source'});}return{accepted,quarantine};}
