import {mountTracking,mountPrizeInterests} from './tracking-ui.mjs';
import {frequencyLeaders} from './leaders.mjs';
let leaderTarget='front3',leaderCount=5,leaderRecent=false;
import {sixDigitSets,sixPrizeTypes} from './six-digit.mjs';
import {evidenceHistory,countEvidence,lowerSets} from './evidence.mjs';
let prize='first',mode='frequency',scope='all',referenceDate='';
const storageKey='hammto-interests-v1';
let interests=[];try{const stored=JSON.parse(localStorage.getItem(storageKey)||'[]');if(Array.isArray(stored))interests=stored.filter(r=>sixPrizeTypes[r.prize]&&/^\d{6}$/.test(r.number)&&(!r.lower2||/^\d{2}$/.test(r.lower2))&&(!r.front3||/^\d{3}$/.test(r.front3))&&(!r.back3||/^\d{3}$/.test(r.back3))).slice(0,100);}catch{}
const rate=e=>e.draws?(100*e.rate).toFixed(1)+'%':'NA';
const evidenceLine=e=>e.draws?e.hitDraws+' / '+e.draws+' งวด ('+rate(e)+')':'ไม่มีข้อมูลที่ใช้เทียบ';

const thaiDate=d=>d?new Date(d+'T12:00:00+07:00').toLocaleDateString('th-TH',{day:'numeric',month:'long',year:'numeric'}):'ยังไม่มีข้อมูล';
export function renderHome({container,history,manifest,draws,download,go}){
 const seed=parseInt(manifest.datasetHash.slice(0,8),16),result=sixDigitSets(history,{prize,mode,seed}),category=sixPrizeTypes[prize],latest=draws.filter(d=>d.verification!=='conflict'&&d.verification!=='demo').at(-1);
 const selectedHistory=evidenceHistory(draws,{scope,referenceDate}),lowers=lowerSets(selectedHistory.rows,seed),fronts=frequencyLeaders(selectedHistory.rows,{target:'front3'}).sets,backs=frequencyLeaders(selectedHistory.rows,{target:'last3'}).sets;
 const leaderKey=leaderTarget==='prize'?prize:leaderTarget,leaderLabel=leaderTarget==='prize'?category.label:({last2:'2 ตัวล่าง',front3:'เลขหน้า 3 ตัว',last3:'เลขท้าย 3 ตัว'})[leaderTarget];
 const leaders=frequencyLeaders(leaderTarget==='prize'?history:draws,{target:leaderKey,k:leaderCount,recent:leaderRecent});
 const leaderPanel=`<section class="leader-panel"><h2>เลขที่ออกบ่อยที่สุดในข้อมูลย้อนหลัง</h2><p>เรียงเปอร์เซ็นต์งวดที่เคยออกจากมากไปน้อย · เป็นสถิติย้อนหลัง ไม่ใช่โอกาสถูกรางวัลงวดหน้า</p><div class="evidence-controls"><label>ประเภทรางวัล<select id="leader-target"><option value="prize">เลข 6 หลักของรางวัลที่เลือก</option><option value="last2">2 ตัวล่าง</option><option value="front3">เลขหน้า 3 ตัว</option><option value="last3">เลขท้าย 3 ตัว</option></select></label><label>จำนวนเลขที่แสดง<select id="leader-count"><option value="5">5 ชุด</option><option value="10">10 ชุด</option><option value="20">20 ชุด</option></select></label><label>ช่วงข้อมูลจัดอันดับ<select id="leader-window"><option value="all">ทั้งหมด</option><option value="recent">20 งวดล่าสุด</option></select></label></div><p>${leaderLabel} · มีผลรางวัลใช้คำนวณ ${leaders.total} งวด · ${thaiDate(leaders.from)} ถึง ${thaiDate(leaders.to)}</p><div class="leader-grid">${leaders.sets.map((r,i)=>`<article><span>รายการที่ ${i+1}</span><strong>${r.number}</strong><b>${(r.rate*100).toFixed(2)}% ของงวดย้อนหลัง</b><p>เคยออก ${r.hits} / ${leaders.total} งวด</p><p class="sample-note">${r.hits<5?'พบซ้ำน้อยกว่า 5 งวด: หลักฐานยังจำกัด':'จำนวนครั้งที่พบยังไม่ยืนยันการทำนาย'} · ตัวอย่าง ${leaders.total} งวด</p><small>ความถี่เท่ากัน ${r.tied} เลข · เรียงเลขน้อยก่อนเมื่อเสมอ</small><details><summary>ดูงวดที่เคยออก</summary>${r.dates.map(thaiDate).join(' · ')}</details><button data-copy="${r.number}">คัดลอก ${r.number}</button>${['front3','last3','last2'].includes(leaderKey)?`<button data-watch="${leaderKey}" data-number="${r.number}">♡ สนใจเลขนี้</button>`:''}</article>`).join('')||'<p>ไม่มีข้อมูลรางวัลนี้ในช่วงที่เลือก</p>'}</div><p>เปอร์เซ็นต์แต่ละเลขบวกกันเป็นโอกาสรวมไม่ได้ โดยเฉพาะรางวัลที่มีหลายเลขต่องวด เลขที่เคยออกบ่อยไม่ได้ยืนยันว่าจะออกซ้ำ</p><p>จำนวนงวดน้อยทำให้เปอร์เซ็นต์ผันผวน เช่น 2/20 = 10% เป็นเพียงความถี่ย้อนหลัง เกณฑ์พบซ้ำน้อยกว่า 5 งวดเป็นข้อความเตือนให้อ่านจำนวนตัวอย่าง ไม่ใช่เกณฑ์รับรองความแม่น</p><div id="prize-interests"></div><button id="save-leaders" ${leaders.sets.length?'':'disabled'}>ดาวน์โหลดเลขและสถิติที่แสดง ↓</button></section>`;
 const interestKey=n=>prize+':'+n;
 const statCard=(r,i)=>{if(prize!=='first')return '';const lower=lowers[i],front=fronts[i]?.number,back=backs[i]?.number,e={whole:countEvidence(selectedHistory.rows,r.number,'firstPrize'),front:countEvidence(selectedHistory.rows,front,'front3'),back:countEvidence(selectedHistory.rows,back,'last3'),lower:lower==null?null:countEvidence(selectedHistory.rows,lower,'last2')};return `<div class="set-evidence"><div><span>เลขหน้า 3 ตัว · คัดแยก</span><b>${front??'—'}</b><small>เทียบรางวัลเลขหน้า 3 ตัว: ${front?evidenceLine(e.front):'ไม่มีข้อมูล'}</small></div><div><span>เลขท้าย 3 ตัว · คัดแยก</span><b>${back??'—'}</b><small>เทียบรางวัลเลขท้าย 3 ตัว: ${back?evidenceLine(e.back):'ไม่มีข้อมูล'}</small></div><div class="lower-pick"><span>2 ตัวล่าง · คัดแยก</span><b>${lower??'—'}</b><small>รางวัลเลขท้าย 2 ตัว: ${e.lower?evidenceLine(e.lower):'ไม่มีข้อมูล'}</small></div><details><summary>สถิติเลขเต็มและงวดที่เคยออก</summary><p>เลขเต็ม ${r.number} ตรงรางวัลที่ 1: ${evidenceLine(e.whole)}</p>${[['หน้า 3 ตัว',e.front],['ท้าย 3 ตัว',e.back],['2 ตัวล่าง',e.lower]].map(([label,v])=>'<p>'+label+': '+(v?.dates.length?v.dates.map(thaiDate).join(' · '):'ไม่พบในช่วงที่เลือก')+'</p>').join('')}<p>นับงวดที่ถูกอย่างน้อยหนึ่งรางวัล ไม่ใช่จำนวนลูกบอล: หน้า 3 ตัว ${e.front.occurrences}/${e.front.observations} ผล, ท้าย 3 ตัว ${e.back.occurrences}/${e.back.observations} ผล</p></details></div>`;};
 container.innerHTML=`<section class="next-hero"><div class="hero-copy"><span class="home-kicker">HAMMTO · ใช้งานแบบง่าย</span><h1>เลขทดลองงวดถัดไป</h1><p>เลือกประเภทรางวัล แล้วดูเลข 6 หลัก 5 ชุดได้เลย</p><div class="home-data-date"><span class="dot"></span> ใช้ผลย้อนหลังถึง ${thaiDate(manifest.lastDate)}</div></div><div class="hero-mark" aria-hidden="true">6<span>หลัก</span><small>5 ชุดเลขทดลอง</small></div></section>
 <section class="pick-panel" aria-labelledby="pick-title"><div class="step-label"><span>1</span> เลือกรางวัลที่อยากดู</div><div class="prize-tabs" role="group" aria-label="ประเภทรางวัลเลขหกหลัก">${Object.entries(sixPrizeTypes).map(([key,v])=>`<button data-prize="${key}" aria-pressed="${key===prize}" class="${key===prize?'selected':''}">${v.label}</button>`).join('')}</div>
 <div class="pick-heading"><div><div class="step-label"><span>2</span> ดูเลขทดลอง 5 ชุด</div><h2 id="pick-title">${category.label}</h2><p>รางวัลละ ${category.amount.toLocaleString('th-TH')} บาท · ${category.count} เลขรางวัล</p></div><span class="method-pill">${mode==='frequency'?'คัดจากความถี่รายหลัก':'สุ่มเลขเพื่อเปรียบเทียบ'}</span></div>
 <div class="honesty-note"><b>ไม่มีเลขชุดใดรับประกันถูก 100%</b><span>ทั้ง 5 ชุดเป็นเลขทดลอง ยังไม่มีหลักฐานว่ามีโอกาสถูกมากกว่าการสุ่ม</span></div>
 ${prize==='first'?`<div class="evidence-controls"><label>สถิติที่ใช้เทียบ<select id="evidence-scope"><option value="all">ทั้งหมดที่มีข้อมูล</option><option value="recent20">20 งวดล่าสุดก่อนวันที่เลือก</option><option value="month">เดือนเดียวกับวันที่เลือก</option><option value="day">วันที่ของเดือนเดียวกัน</option><option value="weekday">วันในสัปดาห์เดียวกัน</option></select></label><label>วันที่งวดที่ต้องการเทียบ (เลือกได้)<input id="evidence-date" type="date" value="${referenceDate}"></label></div><p class="evidence-caption">${selectedHistory.needsDate?'โปรดเลือกวันที่งวดก่อนเทียบปฏิทิน':('เทียบ '+selectedHistory.rows.length+' งวด'+(referenceDate?' ก่อน '+thaiDate(referenceDate):' ในฐานข้อมูล'))} · เปอร์เซ็นต์คือสัดส่วนที่เคยออก ไม่ใช่ความมั่นใจงวดหน้า</p><p class="evidence-caption">หน้า 3 ตัว ท้าย 3 ตัว และ 2 ตัวล่าง คัดแยกตามประวัติรางวัลแต่ละประเภทในช่วงที่เลือก ไม่ได้ตัดจากเลข 6 หลัก · เลข 6 หลักยังใช้ประวัติทั้งหมด</p>`:''}
 ${leaderPanel}
 <h3>ชุดเลข 6 หลักจากสูตรความถี่รายหลัก (ทดลอง)</h3>
 <div class="six-cards ${prize==='first'?'with-evidence':''}">${result.sets.map((r,i)=>`<article class="six-card"><div class="ticket-top"><span>ชุดที่ ${i+1}</span><span>6 หลัก</span></div><strong class="six-number" aria-label="ชุดที่ ${i+1} เลข ${r.number}">${r.number}</strong>${statCard(r,i)}<button class="interest-number" data-interest="${r.number}" data-front="${prize==='first'?(fronts[i]?.number??''):''}" data-back="${prize==='first'?(backs[i]?.number??''):''}" data-lower="${prize==='first'?(lowers[i]??''):''}" aria-pressed="${interests.some(v=>v.key===interestKey(r.number))}">${interests.some(v=>v.key===interestKey(r.number))?'♥ สนใจแล้ว':'♡ สนใจชุดนี้'}</button><button class="copy-number" data-copy="${r.number}" aria-label="คัดลอกเลข ${r.number}">คัดลอกเลข ⧉</button></article>`).join('')}</div>
 ${result.sets.length?'':'<p class="empty">ข้อมูลรางวัลนี้ยังไม่พร้อม จึงยังไม่สร้างเลขจากความถี่</p>'}
 
 <details class="interest-list" ${interests.length?'open':''}><summary>ชุดที่สนใจ (${interests.length}) · บันทึกในเครื่องนี้</summary><div>${interests.map((v,i)=>`<span class="saved-set">${sixPrizeTypes[v.prize].label} <b>${v.number}</b>${v.front3?' · หน้า '+v.front3:''}${v.back3?' · ท้าย '+v.back3:''}${v.lower2?' · ล่าง '+v.lower2:''}<button data-remove="${i}" aria-label="ลบเลข ${v.number} จากรายการสนใจ">ลบ</button></span>`).join('')}</div><button id="export-interests" ${interests.length?'':'disabled'}>บันทึกรายการที่สนใจ ↓</button><p>รายการส่วนตัวไม่ส่งไปยัง Google Sheets และอาจหายเมื่อคุณล้างข้อมูลเบราว์เซอร์</p></details>
 <div class="home-actions"><button class="primary-action" id="save-five" ${result.sets.length?'':'disabled'}>บันทึกเลขทั้ง 5 ชุด ↓</button><button id="latest-results">ดูผลรางวัลล่าสุด →</button><span id="copy-status" role="status"></span></div>
 <details class="home-explain"><summary>เลขเหล่านี้มาจากไหน?</summary><p>ใช้ข้อมูล ${result.draws} งวด รวม ${result.observations.toLocaleString('th-TH')} เลขของ${category.label} จาก API สำนักงานสลากฯ ถึง ${thaiDate(result.cutoff)} แยกนับตัวเลขในแต่ละหลัก เติมค่าปรับเรียบ 1 แล้วจัดอันดับจากผลคูณของสัดส่วนรายหลัก</p><p>วิธี 6 หลักนี้ยังไม่ผ่าน backtest หรือ calibration เพื่อรับรองความสามารถทำนาย และรางวัลข้างเคียงมีความสัมพันธ์กับรางวัลที่ 1 ไม่ใช่การสุ่มอิสระ การแสดง 5 ชุดต่อหมวดไม่ได้หมายความว่าจะถูกครบทุกหมวด</p><label>วิธีเลือกชุดเลข<select id="six-mode"><option value="frequency" ${mode==='frequency'?'selected':''}>ความถี่รายหลัก (ทดลอง)</option><option value="random" ${mode==='random'?'selected':''}>สุ่ม 5 ชุดเพื่อเปรียบเทียบ</option></select></label><p>ชุดเลขคงเดิมเมื่อใช้ข้อมูลและวิธีเดิม · เปลี่ยนเมื่อ snapshot ข้อมูลเปลี่ยน · เวอร์ชัน ${result.version}</p><a href="./data/six-digit-sets.json" download>ดาวน์โหลดวิธีคำนวณและเลขทุกหมวด JSON</a></details></section>
 <section class="leader-panel" id="tracking-results">กำลังโหลดบันทึกการติดตาม…</section>
 <div class="home-bottom"><section class="quick-result"><div class="mini-label">ผลจริงล่าสุด · ${thaiDate(latest?.drawDate)}</div><div class="quick-result-body"><div><span>รางวัลที่ 1</span><b>${latest?.firstPrize??'—'}</b></div><div><span>เลขท้าย 2 ตัว</span><b>${latest?.last2??'—'}</b></div></div><button id="open-history">ดูผลย้อนหลังทั้งหมด →</button></section><section class="plain-fact"><span class="mini-label">เข้าใจโอกาสให้ตรงกัน</span><h2>5 เลข ไม่เท่ากับถูกแน่นอน</h2><p>สำหรับรางวัลที่ 1 เลือก 5 เลขไม่ซ้ำจาก 1,000,000 เลข<br><strong>โอกาสพื้นฐานรวม 0.0005%</strong> ภายใต้การสุ่มสม่ำเสมอ</p><p class="small-note">ตัวเลขนี้ใช้กับรางวัลที่ 1 เท่านั้น ไม่ใช่โอกาสรวมทุกรางวัล</p></section></div>
 <div class="prize-footnote">สลาก L6 มีรางวัลที่ 1–5 และรางวัลข้างเคียงรางวัลที่ 1 <b>ไม่มีประเภทรางวัลที่ 6</b> · <a href="https://www.prd.go.th/th/content/page/index/id/219583" target="_blank" rel="noopener">ดูประเภทรางวัลทางการ ↗</a></div>`;
 mountPrizeInterests(container,download);mountTracking(container.querySelector('#tracking-results'));
 const refresh=()=>renderHome({container,history,manifest,draws,download,go});
 container.querySelector('#leader-target').value=leaderTarget;container.querySelector('#leader-count').value=String(leaderCount);container.querySelector('#leader-window').value=leaderRecent?'recent':'all';
 container.querySelector('#leader-target').onchange=e=>{leaderTarget=e.target.value;refresh();};container.querySelector('#leader-count').onchange=e=>{leaderCount=Number(e.target.value);refresh();};container.querySelector('#leader-window').onchange=e=>{leaderRecent=e.target.value==='recent';refresh();};
 container.querySelector('#save-leaders').onclick=()=>download('HAMMTO-historical-frequency.json',JSON.stringify({label:leaderLabel,target:leaderKey,window:leaderRecent?'recent20':'all',datasetHash:manifest.datasetHash,warning:'Historical frequency only; not future winning probability',...leaders},null,2));
 const saveInterests=next=>{try{localStorage.setItem(storageKey,JSON.stringify(next));interests=next;refresh();}catch{container.querySelector('#copy-status').textContent='บันทึกในเครื่องไม่ได้ กรุณาดาวน์โหลดรายการแทน';}};
 container.querySelectorAll('[data-interest]').forEach(b=>b.onclick=()=>{const key=interestKey(b.dataset.interest);const existing=interests.some(v=>v.key===key);if(!existing&&interests.length>=100){container.querySelector('#copy-status').textContent='เก็บได้สูงสุด 100 ชุด กรุณาลบรายการเก่าก่อน';return;}saveInterests(existing?interests.filter(v=>v.key!==key):[...interests,{key,prize,number:b.dataset.interest,lower2:b.dataset.lower||null,front3:b.dataset.front||null,back3:b.dataset.back||null,datasetHash:manifest.datasetHash,dataThrough:manifest.lastDate,savedAt:new Date().toISOString()}]);});
 container.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>saveInterests(interests.filter((_,i)=>i!==Number(b.dataset.remove))));
 container.querySelector('#export-interests').onclick=()=>download('HAMMTO-interests.json',JSON.stringify({warning:'เลขทดลอง ไม่ใช่การรับประกันผล',interests},null,2));
 if(container.querySelector('#evidence-scope')){container.querySelector('#evidence-scope').value=scope;container.querySelector('#evidence-scope').onchange=e=>{scope=e.target.value;refresh();};container.querySelector('#evidence-date').onchange=e=>{referenceDate=e.target.value;refresh();};}
 container.querySelectorAll('[data-prize]').forEach(b=>b.onclick=()=>{prize=b.dataset.prize;renderHome({container,history,manifest,draws,download,go});});
 container.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);container.querySelector('#copy-status').textContent='คัดลอก '+b.dataset.copy+' แล้ว';}catch{container.querySelector('#copy-status').textContent='คัดลอกไม่ได้ กรุณากดบันทึกเลขทั้ง 5 ชุด';}});
 container.querySelector('#save-five').onclick=()=>download('HAMMTO-5-sets-'+prize+'.txt',`${category.label} — เลขทดลองสำหรับงวดหลัง ${manifest.lastDate}\n${result.sets.map((r,i)=>`${i+1}. ${r.number}${prize==='first'?' | เลขหน้า 3 ตัวคัดแยก '+(fronts[i]?.number??'ไม่มีข้อมูล')+' | เลขท้าย 3 ตัวคัดแยก '+(backs[i]?.number??'ไม่มีข้อมูล')+' | 2 ตัวล่างคัดแยก '+(lowers[i]??'ไม่มีข้อมูล'):''}`).join('\n')}\n\nไม่มีเลขรับประกันถูก 100% ยังไม่พบหลักฐานว่าเหนือการสุ่ม\nวิธี: ${mode} | รุ่น: ${result.version}\nข้อมูล: ${result.draws} งวด / ${result.observations} เลข\nDataset SHA-256: ${manifest.datasetHash}\nSeed: ${seed}\nไม่ใช่หลักฐานประทับเวลาก่อนออกรางวัล\n`,'text/plain');
 container.querySelector('#six-mode').onchange=e=>{mode=e.target.value;renderHome({container,history,manifest,draws,download,go});};
 container.querySelector('#latest-results').onclick=()=>go('overview');container.querySelector('#open-history').onclick=()=>go('history');
}
