import {sixDigitSets,sixPrizeTypes} from './six-digit.mjs';
let prize='first',mode='frequency';
const thaiDate=d=>d?new Date(d+'T12:00:00+07:00').toLocaleDateString('th-TH',{day:'numeric',month:'long',year:'numeric'}):'ยังไม่มีข้อมูล';
export function renderHome({container,history,manifest,draws,download,go}){
 const seed=parseInt(manifest.datasetHash.slice(0,8),16),result=sixDigitSets(history,{prize,mode,seed}),category=sixPrizeTypes[prize],latest=draws.filter(d=>d.verification!=='conflict'&&d.verification!=='demo').at(-1);
 container.innerHTML=`<section class="next-hero"><div class="hero-copy"><span class="home-kicker">HAMMTO · ใช้งานแบบง่าย</span><h1>เลขทดลองงวดถัดไป</h1><p>เลือกประเภทรางวัล แล้วดูเลข 6 หลัก 5 ชุดได้เลย</p><div class="home-data-date"><span class="dot"></span> ใช้ผลย้อนหลังถึง ${thaiDate(manifest.lastDate)}</div></div><div class="hero-mark" aria-hidden="true">6<span>หลัก</span><small>5 ชุดเลขทดลอง</small></div></section>
 <section class="pick-panel" aria-labelledby="pick-title"><div class="step-label"><span>1</span> เลือกรางวัลที่อยากดู</div><div class="prize-tabs" role="group" aria-label="ประเภทรางวัลเลขหกหลัก">${Object.entries(sixPrizeTypes).map(([key,v])=>`<button data-prize="${key}" aria-pressed="${key===prize}" class="${key===prize?'selected':''}">${v.label}</button>`).join('')}</div>
 <div class="pick-heading"><div><div class="step-label"><span>2</span> ดูเลขทดลอง 5 ชุด</div><h2 id="pick-title">${category.label}</h2><p>รางวัลละ ${category.amount.toLocaleString('th-TH')} บาท · ${category.count} เลขรางวัล</p></div><span class="method-pill">${mode==='frequency'?'คัดจากความถี่รายหลัก':'สุ่มเลขเพื่อเปรียบเทียบ'}</span></div>
 <div class="honesty-note"><b>ไม่มีเลขชุดใดรับประกันถูก 100%</b><span>ทั้ง 5 ชุดเป็นเลขทดลอง ยังไม่มีหลักฐานว่ามีโอกาสถูกมากกว่าการสุ่ม</span></div>
 <div class="six-cards">${result.sets.map((r,i)=>`<article class="six-card"><div class="ticket-top"><span>ชุดที่ ${i+1}</span><span>6 หลัก</span></div><strong class="six-number" aria-label="ชุดที่ ${i+1} เลข ${r.number}">${r.number}</strong><button class="copy-number" data-copy="${r.number}" aria-label="คัดลอกเลข ${r.number}">คัดลอกเลข ⧉</button></article>`).join('')}</div>
 ${result.sets.length?'':'<p class="empty">ข้อมูลรางวัลนี้ยังไม่พร้อม จึงยังไม่สร้างเลขจากความถี่</p>'}
 
 <div class="home-actions"><button class="primary-action" id="save-five" ${result.sets.length?'':'disabled'}>บันทึกเลขทั้ง 5 ชุด ↓</button><button id="latest-results">ดูผลรางวัลล่าสุด →</button><span id="copy-status" role="status"></span></div>
 <details class="home-explain"><summary>เลขเหล่านี้มาจากไหน?</summary><p>ใช้ข้อมูล ${result.draws} งวด รวม ${result.observations.toLocaleString('th-TH')} เลขของ${category.label} จาก API สำนักงานสลากฯ ถึง ${thaiDate(result.cutoff)} แยกนับตัวเลขในแต่ละหลัก เติมค่าปรับเรียบ 1 แล้วจัดอันดับจากผลคูณของสัดส่วนรายหลัก</p><p>วิธี 6 หลักนี้ยังไม่ผ่าน backtest หรือ calibration เพื่อรับรองความสามารถทำนาย และรางวัลข้างเคียงมีความสัมพันธ์กับรางวัลที่ 1 ไม่ใช่การสุ่มอิสระ การแสดง 5 ชุดต่อหมวดไม่ได้หมายความว่าจะถูกครบทุกหมวด</p><label>วิธีเลือกชุดเลข<select id="six-mode"><option value="frequency" ${mode==='frequency'?'selected':''}>ความถี่รายหลัก (ทดลอง)</option><option value="random" ${mode==='random'?'selected':''}>สุ่ม 5 ชุดเพื่อเปรียบเทียบ</option></select></label><p>ชุดเลขคงเดิมเมื่อใช้ข้อมูลและวิธีเดิม · เปลี่ยนเมื่อ snapshot ข้อมูลเปลี่ยน · เวอร์ชัน ${result.version}</p><a href="./data/six-digit-sets.json" download>ดาวน์โหลดวิธีคำนวณและเลขทุกหมวด JSON</a></details></section>
 <div class="home-bottom"><section class="quick-result"><div class="mini-label">ผลจริงล่าสุด · ${thaiDate(latest?.drawDate)}</div><div class="quick-result-body"><div><span>รางวัลที่ 1</span><b>${latest?.firstPrize??'—'}</b></div><div><span>เลขท้าย 2 ตัว</span><b>${latest?.last2??'—'}</b></div></div><button id="open-history">ดูผลย้อนหลังทั้งหมด →</button></section><section class="plain-fact"><span class="mini-label">เข้าใจโอกาสให้ตรงกัน</span><h2>5 เลข ไม่เท่ากับถูกแน่นอน</h2><p>สำหรับรางวัลที่ 1 เลือก 5 เลขไม่ซ้ำจาก 1,000,000 เลข<br><strong>โอกาสพื้นฐานรวม 0.0005%</strong> ภายใต้การสุ่มสม่ำเสมอ</p><p class="small-note">ตัวเลขนี้ใช้กับรางวัลที่ 1 เท่านั้น ไม่ใช่โอกาสรวมทุกรางวัล</p></section></div>
 <div class="prize-footnote">สลาก L6 มีรางวัลที่ 1–5 และรางวัลข้างเคียงรางวัลที่ 1 <b>ไม่มีประเภทรางวัลที่ 6</b> · <a href="https://www.prd.go.th/th/content/page/index/id/219583" target="_blank" rel="noopener">ดูประเภทรางวัลทางการ ↗</a></div>`;
 container.querySelectorAll('[data-prize]').forEach(b=>b.onclick=()=>{prize=b.dataset.prize;renderHome({container,history,manifest,draws,download,go});});
 container.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);container.querySelector('#copy-status').textContent='คัดลอก '+b.dataset.copy+' แล้ว';}catch{container.querySelector('#copy-status').textContent='คัดลอกไม่ได้ กรุณากดบันทึกเลขทั้ง 5 ชุด';}});
 container.querySelector('#save-five').onclick=()=>download('HAMMTO-5-sets-'+prize+'.txt',`${category.label} — เลขทดลองสำหรับงวดหลัง ${manifest.lastDate}\n${result.sets.map((r,i)=>`${i+1}. ${r.number}`).join('\n')}\n\nไม่มีเลขรับประกันถูก 100% ยังไม่พบหลักฐานว่าเหนือการสุ่ม\nวิธี: ${mode} | รุ่น: ${result.version}\nข้อมูล: ${result.draws} งวด / ${result.observations} เลข\nDataset SHA-256: ${manifest.datasetHash}\nSeed: ${seed}\nไม่ใช่หลักฐานประทับเวลาก่อนออกรางวัล\n`,'text/plain');
 container.querySelector('#six-mode').onchange=e=>{mode=e.target.value;renderHome({container,history,manifest,draws,download,go});};
 container.querySelector('#latest-results').onclick=()=>go('overview');container.querySelector('#open-history').onclick=()=>go('history');
}
