import {trackedTargets} from './tracking.mjs';
const esc=x=>String(x??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=n=>n==null?'ยังไม่มีผล':(n*100).toFixed(2)+'%';
const key='hammto-prize-interests-v1';
export function mountPrizeInterests(container,download){
 let saved=[];try{saved=JSON.parse(localStorage.getItem(key)||'[]').filter(r=>trackedTargets[r.target]&&new RegExp('^\\d{'+(r.target==='last2'?2:3)+'}$').test(r.number)).slice(0,100);}catch{}
 const host=container.querySelector('#prize-interests');
 const paint=()=>{host.innerHTML='<h3>รายการสนใจแยกประเภทรางวัล ('+saved.length+')</h3><p>เก็บเฉพาะเบราว์เซอร์นี้ ไม่ใช่รายการซื้อหรือเลขที่ระบบบันทึกก่อนงวด</p>'+saved.map((r,i)=>'<span class="saved-set">'+trackedTargets[r.target]+' <b>'+r.number+'</b><button data-watch-remove="'+i+'">ลบ</button></span>').join('')+'<p id="watch-status" role="status"></p><button id="watch-export" '+(saved.length?'':'disabled')+'>ดาวน์โหลดรายการสนใจ</button>';
 container.querySelectorAll('[data-watch]').forEach(b=>{const active=saved.some(r=>r.target===b.dataset.watch&&r.number===b.dataset.number);b.textContent=active?'♥ สนใจแล้ว':'♡ สนใจเลขนี้';b.setAttribute('aria-pressed',String(active));});
 host.querySelectorAll('[data-watch-remove]').forEach(b=>b.onclick=()=>save(saved.filter((_,i)=>i!==Number(b.dataset.watchRemove))));host.querySelector('#watch-export').onclick=()=>download('HAMMTO-prize-interests.json',JSON.stringify(saved,null,2));};
 const save=next=>{try{localStorage.setItem(key,JSON.stringify(next));saved=next;paint();}catch{host.querySelector('#watch-status').textContent='บันทึกไม่ได้ เบราว์เซอร์อาจปิดการเก็บข้อมูล';}};
 container.querySelectorAll('[data-watch]').forEach(b=>b.onclick=()=>{const found=saved.some(r=>r.target===b.dataset.watch&&r.number===b.dataset.number);if(!found&&saved.length>=100){host.querySelector('#watch-status').textContent='เก็บได้ 100 เลข กรุณาลบรายการเก่าก่อน';return;}save(found?saved.filter(r=>!(r.target===b.dataset.watch&&r.number===b.dataset.number)):[...saved,{target:b.dataset.watch,number:b.dataset.number,savedAt:new Date().toISOString()}]);});paint();
}
let loaded;
export async function mountTracking(host){
 try{loaded??=Promise.all(['tracking','tracking-backtests'].map(n=>fetch('./data/'+n+'.json').then(r=>{if(!r.ok)throw Error();return r.json();})));const [tracking,backtests]=await loaded;if(!host.isConnected)return;
 const done=tracking.records.filter(r=>r.evaluation),wins=done.filter(r=>r.evaluation.hit).length;
 host.innerHTML='<h2>ติดตามผลจริงและทดสอบย้อนหลัง</h2><p><b>ผลจริงที่บันทึกก่อนงวด: '+wins+' งวดถูก / '+done.length+' รายการที่ตรวจแล้ว</b> · รอตรวจ '+tracking.records.filter(r=>!r.evaluation).length+' รายการ (นับแยกประเภทรางวัล)</p><p>ล็อก 5 เลขจากความถี่ทั้งหมด แล้วตรวจงวดแรกที่มีผลทางการหลังวันที่บันทึกตามเวลาไทย ไม่รวมงวดวันเดียวกัน ชุดที่ล็อกไม่เปลี่ยนตามตัวกรองหน้าเว็บ ข้อมูลที่ยังดึงไม่ครบอาจทำให้ตรวจล่าช้า</p><p>ยังไม่ใช่หลักฐานว่าทำนายแม่น และไม่ใช่ระบบรับรองเวลาแก้ไขไม่ได้ ตรวจประวัติการเผยแพร่ได้บน GitHub</p><div class="leader-grid">'+tracking.records.slice().reverse().map(r=>'<article><span>'+esc(trackedTargets[r.target])+'</span><b>'+r.picks.map(esc).join(' · ')+'</b><p>บันทึก '+esc(new Date(r.recordedAt).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'}))+' · ใช้ข้อมูลถึง '+esc(r.dataThrough)+'</p><p>'+(r.evaluation?'งวด '+esc(r.evaluation.drawDate)+' · '+(r.evaluation.hit?'ถูก: '+r.evaluation.matched.map(esc).join(' · '):'ไม่ถูก')+'<br>ผลจริง '+r.evaluation.actual.map(esc).join(' · '):'รอผลงวดหลังวันที่บันทึก')+'</p><a href="'+esc(r.runUrl)+'" target="_blank" rel="noopener">ประวัติการเผยแพร่ ↗</a></article>').join('')+'</div><details><summary>ผลทดสอบย้อนหลังเทียบการสุ่ม — รวมงวดแพ้</summary><p>วิธีตายตัว: ความถี่รายงวด 5 เลข ประวัติขยาย เริ่มหลังมีข้อมูล 30 งวด ไม่เลือกสูตรชนะภายหลัง นี่เป็นผลย้อนหลัง ไม่ใช่ผลก่อนงวดหรือความมั่นใจของเลขแต่ละตัว</p><div class="table-wrap"><table><thead><tr><th>รางวัล</th><th>งวดทดสอบ</th><th>สูตรถูก</th><th>สุ่ม 5 เลขถูก</th><th>ค่าเฉลี่ยฐานสุ่ม</th><th>ช่วงความไม่แน่นอน 95%</th></tr></thead><tbody>'+backtests.results.map(r=>'<tr><td>'+esc(trackedTargets[r.target])+'</td><td>'+r.n+'</td><td>'+r.hits+'/'+r.n+' ('+pct(r.rate)+')</td><td>'+r.randomHits+'/'+r.n+' ('+pct(r.randomRate)+')</td><td>'+pct(r.expectedRandomRate)+'</td><td>'+(r.ci?r.ci.map(pct).join(' – '):'ไม่มีข้อมูล')+'</td></tr>').join('')+'</tbody></table></div><p>ฐานสุ่มคือค่าเฉลี่ยทางคณิตศาสตร์สำหรับการเลือก 5 เลขไม่ซ้ำ เทียบจำนวนผลจริงที่ต่างกันในแต่ละงวด อีกคอลัมน์เป็นการสุ่มหนึ่งชุดต่อหนึ่งงวดด้วย seed คงที่ ผลครั้งเดียวอาจผันผวน ช่วง 95% ใช้สมมติฐานงวดอิสระ ไม่ใช่การยืนยันความได้เปรียบหรือช่วงของเลขที่เลือก</p><a href="./data/tracking-backtests.json" download>ดาวน์โหลดชุดเลข ผลจริง และผลถูก/ผิดทุกงวด</a></details><a href="./data/tracking.json" download>ดาวน์โหลดบันทึกก่อนงวดและผลตรวจทั้งหมด</a>';
 }catch{loaded=undefined;host.textContent='ยังโหลดบันทึกการติดตามไม่ได้ กรุณารีเฟรชหน้าเว็บ';}
}
